### ISSUE TITLE
Deploy HTML file to gh-pages

### ISSUE THREAD

**Issue by cmgriffing** [tg12/gpt_jailbreak_status#1]
I see that you have the html file hosted on your personal domain. My guess is that this process is done manually.

Github Pages is a free hosting service for static html and it can be wired up to redeploy when you push new changes.

The url would end up looking like:
`https://tg12.github.io/gpt_jailbreak_status/gpt_jb.html`

It can be added simply with a Github Action.
I would be happy to implement it with a PR. No worries if not.

**Comment by tg12** [comment]
Hi mate, I have added a section to my scripts that publishes the HTML file to my webserver links on the README. I don't see a need right now but if I do I will holla. Thanks for the offer.
